{{--
@component x-plume::breadcrumb.separator
@description Visual separator between breadcrumb items. Auto-generated by x-plume::breadcrumb but can be used manually.
@usage
<x-plume::breadcrumb.separator>
    <span class="text-xs">/</span>
</x-plume::breadcrumb.separator>
--}}
<li role="presentation" aria-hidden="true"
    {{ $attributes->merge(['class' => '[&>.icon]:size-2.5 text-foreground/30 dark:text-background-400/50']) }}>
    @if ($slot->isNotEmpty())
        {{ $slot }}
    @else
        <x-plume::icon i="icon-[fluent--chevron-right-24-regular]" />
    @endif
</li>
